# Generated by Django 5.2.14 on 2026-09-21 16:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0801_realmexport_backfill_export_from_prior_server_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("number", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("lease_epoch", models.PositiveBigIntegerField()),
                ("lease_expires_at", models.DateTimeField()),
                ("claim_key", models.UUIDField(default=uuid.uuid4)),
                ("configuration_digest", models.CharField(default="", max_length=64)),
                ("descriptor_digest", models.CharField(max_length=64)),
                ("descriptor", models.JSONField(default=dict)),
                ("adapter_version", models.CharField(default="", max_length=100)),
                ("provider_config_version", models.PositiveIntegerField(null=True)),
                ("base_commit", models.CharField(default="", max_length=64)),
                ("tree_hash", models.CharField(default="", max_length=64)),
                ("workspace_reference", models.CharField(default="", max_length=200)),
                ("workspace_prepared_at", models.DateTimeField(null=True)),
                ("runtime_session_reference", models.CharField(default="", max_length=512)),
                ("input_cursor", models.PositiveBigIntegerField(default=0)),
                ("event_cursor", models.PositiveBigIntegerField(default=0)),
                (
                    "process_state",
                    models.CharField(
                        choices=[
                            ("starting", "starting"),
                            ("active", "active"),
                            ("stopping", "stopping"),
                            ("stopped", "stopped"),
                            ("unknown", "unknown"),
                        ],
                        default="starting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("stopped_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(max_length=30)),
                ("checksum", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("storage_ref", models.CharField(max_length=512)),
                ("filename", models.CharField(default="artifact", max_length=255)),
                (
                    "media_type",
                    models.CharField(default="application/octet-stream", max_length=100),
                ),
                ("expires_at", models.DateTimeField()),
                ("unavailable_at", models.DateTimeField(null=True)),
                ("acl_scope", models.JSONField(default=dict)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentattempt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("base_commit", models.CharField(default="", max_length=64)),
                ("tree_hash", models.CharField(default="", max_length=64)),
                ("summary", models.TextField()),
                ("context_refs", models.JSONField(default=list)),
                ("artifact_ids", models.JSONField(default=list)),
                ("remaining_work", models.JSONField(default=list)),
                ("next_step", models.TextField()),
                ("adapter_session_ref", models.CharField(default="", max_length=512)),
                ("input_cursor", models.PositiveBigIntegerField(default=0)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="zerver.agentattempt",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="source_checkpoint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resumed_attempts",
                to="zerver.agentcheckpoint",
            ),
        ),
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("scope", models.JSONField(default=dict)),
                ("session_reference", models.CharField(default="", max_length=512)),
                (
                    "anchor_message",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trigger_kind",
                    models.CharField(
                        choices=[
                            ("mention", "mention"),
                            ("direct_message", "direct_message"),
                            ("manual", "manual"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "job_kind",
                    models.CharField(
                        choices=[("answer", "answer"), ("code", "code")],
                        default="answer",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_target",
                    models.CharField(
                        choices=[
                            ("answer", "answer"),
                            ("patch", "patch"),
                            ("draft_pr", "draft_pr"),
                        ],
                        default="answer",
                        max_length=20,
                    ),
                ),
                ("request", models.TextField()),
                ("base_ref", models.CharField(default="", max_length=200)),
                ("idempotency_key", models.UUIDField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("admission_revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("queued", "queued"),
                            ("running", "running"),
                            ("waiting_for_input", "waiting_for_input"),
                            ("waiting_for_approval", "waiting_for_approval"),
                            ("blocked", "blocked"),
                            ("verifying", "verifying"),
                            ("cancel_requested", "cancel_requested"),
                            ("cancelled", "cancelled"),
                            ("interrupted", "interrupted"),
                            ("failed", "failed"),
                            ("completed", "completed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("inspect", "inspect"),
                            ("plan", "plan"),
                            ("edit", "edit"),
                            ("verify", "verify"),
                            ("review", "review"),
                            ("deliver", "deliver"),
                        ],
                        default="inspect",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("blocked_reason", models.CharField(default="", max_length=200)),
                ("start_deadline", models.DateTimeField(null=True)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
                ("policy", models.JSONField(default=dict)),
                ("budget", models.JSONField(default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentconversation"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "result_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_result_jobs",
                        to="zerver.message",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_source_jobs",
                        to="zerver.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("client_key", models.UUIDField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("sequence", models.PositiveBigIntegerField()),
                ("input_type", models.CharField(default="steering", max_length=20)),
                ("text", models.TextField()),
                (
                    "delivery_state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("delivered", "delivered"),
                            ("applied", "applied"),
                            ("delivery_uncertain", "delivery_uncertain"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("applied_at", models.DateTimeField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "delivered_attempt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentattempt",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_id", models.UUIDField(default=uuid.uuid4)),
                ("sequence", models.PositiveBigIntegerField()),
                ("attempt_sequence", models.PositiveBigIntegerField(null=True)),
                ("authority", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=80)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentattempt",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
            ),
        ),
        migrations.CreateModel(
            name="AgentOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("operation_id", models.UUIDField(unique=True)),
                ("tool_class", models.CharField(max_length=40)),
                ("argument_digest", models.CharField(max_length=64)),
                ("arguments", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "proposed"),
                            ("authorized", "authorized"),
                            ("started", "started"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("outcome_unknown", "outcome_unknown"),
                            ("cancelled", "cancelled"),
                        ],
                        default="proposed",
                        max_length=30,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("remote_receipt", models.JSONField(default=None, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentattempt"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("operation_hash", models.CharField(max_length=64)),
                ("policy_version", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("tree_hash", models.CharField(max_length=64)),
                ("arguments", models.JSONField(default=dict)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                            ("cancelled", "cancelled"),
                            ("consumed", "consumed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("nonce", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("decided_at", models.DateTimeField(null=True)),
                ("consumed_at", models.DateTimeField(null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentattempt"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentoperation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivery_key", models.CharField(max_length=200, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("payload_ref", models.UUIDField(null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("delivered_at", models.DateTimeField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("mode", models.CharField(default="acp", max_length=20)),
                ("adapter_id", models.CharField(max_length=80)),
                ("adapter_version", models.CharField(max_length=100)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                (
                    "desired_state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("enabled", "enabled"),
                            ("paused", "paused"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[("answer", "answer"), ("code", "code")],
                        default="answer",
                        max_length=20,
                    ),
                ),
                (
                    "readiness_state",
                    models.CharField(
                        choices=[
                            ("unchecked", "unchecked"),
                            ("checking", "checking"),
                            ("ready", "ready"),
                            ("needs_action", "needs_action"),
                            ("error", "error"),
                        ],
                        default="unchecked",
                        max_length=20,
                    ),
                ),
                ("enabled_revision", models.PositiveIntegerField(null=True)),
                ("readiness_revision", models.PositiveIntegerField(null=True)),
                ("readiness_digest", models.CharField(default="", max_length=64)),
                ("readiness_configuration_digest", models.CharField(default="", max_length=64)),
                ("readiness_configuration", models.JSONField(default=None, null=True)),
                ("capability_report", models.JSONField(default=dict)),
                ("archived_at", models.DateTimeField(null=True)),
                ("policy", models.JSONField(default=dict)),
                ("budget", models.JSONField(default=dict)),
                (
                    "bot_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentjob",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentprofile"
            ),
        ),
        migrations.CreateModel(
            name="AgentDispatchReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trigger_kind",
                    models.CharField(
                        choices=[
                            ("mention", "mention"),
                            ("direct_message", "direct_message"),
                            ("manual", "manual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("decision", models.CharField(max_length=20)),
                ("reason", models.CharField(default="", max_length=200)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentprofile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentprofile"
            ),
        ),
        migrations.CreateModel(
            name="AgentProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("base_url", models.URLField(max_length=2048)),
                ("api_mode", models.CharField(default="chat_completions", max_length=30)),
                ("model_id", models.CharField(max_length=200)),
                ("allowed_models", models.JSONField(default=list)),
                ("local_credential_ref", models.CharField(default="", max_length=200)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("context_window_tokens", models.PositiveIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("data_scope", models.JSONField(default=list)),
                ("network_policy", models.JSONField(default=dict)),
                ("capability_report", models.JSONField(default=dict)),
                ("disabled_at", models.DateTimeField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="provider",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentprovider"
            ),
        ),
        migrations.CreateModel(
            name="AgentRealmSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("enabled", models.BooleanField(default=False)),
                ("retention_cleanup_enabled", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("active_job_limit", models.PositiveIntegerField(default=2)),
                ("queued_job_limit", models.PositiveIntegerField(default=100)),
                ("profile_queue_limit", models.PositiveIntegerField(default=20)),
                ("event_retention_days", models.PositiveIntegerField(default=30)),
                ("artifact_retention_days", models.PositiveIntegerField(default=7)),
                ("approval_retention_days", models.PositiveIntegerField(default=90)),
                ("send_retention_days", models.PositiveIntegerField(default=30)),
                (
                    "realm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("workspace_alias", models.CharField(max_length=80)),
                ("canonical_origin", models.CharField(default="", max_length=2048)),
                ("allowed_refs", models.JSONField(default=list)),
                ("required_checks", models.JSONField(default=list)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("disabled_at", models.DateTimeField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="default_repository",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrepository"
            ),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="repository",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrepository"
            ),
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="repository",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrepository"
            ),
        ),
        migrations.CreateModel(
            name="AgentContextRef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(max_length=20)),
                ("scope", models.JSONField(default=dict)),
                ("validated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attachment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zerver.attachment",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentjob"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentrepository",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentRunner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("fingerprint", models.CharField(max_length=128)),
                ("version", models.CharField(default="", max_length=100)),
                ("platform", models.CharField(default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "online"),
                            ("offline", "offline"),
                            ("unknown", "unknown"),
                            ("revoked", "revoked"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat_at", models.DateTimeField(null=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("catalog_revision", models.PositiveIntegerField(default=1)),
                ("catalog_report", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentrepository",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
            ),
        ),
        migrations.AddField(
            model_name="agentprovider",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
            ),
        ),
        migrations.CreateModel(
            name="AgentPairing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("device_name", models.CharField(max_length=200)),
                ("fingerprint", models.CharField(max_length=128)),
                ("polling_secret_hash", models.CharField(max_length=128, unique=True)),
                ("user_code_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(null=True)),
                ("exchanged_at", models.DateTimeField(null=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("state", models.CharField(default="pending", max_length=20)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "runner",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentrunner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentjob",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
            ),
        ),
        migrations.CreateModel(
            name="AgentGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("target_kind", models.CharField(default="profile", max_length=20)),
                ("scope", models.JSONField(default=None, null=True)),
                ("actions", models.JSONField(default=list)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField(null=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_agent_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "principal_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.usergroup",
                    ),
                ),
                (
                    "principal_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentprofile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentprovider",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentrepository",
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentrunner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
            ),
        ),
        migrations.CreateModel(
            name="AgentRunnerCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("refresh_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("refresh_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("rotated_at", models.DateTimeField(null=True)),
                (
                    "parent",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentrunnercredential",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ciphertext", models.BinaryField()),
                ("wrapped_key", models.BinaryField()),
                ("key_id", models.CharField(max_length=200)),
                ("encryption_version", models.PositiveIntegerField(default=1)),
                ("secret_type", models.CharField(default="provider", max_length=40)),
                ("version", models.PositiveIntegerField(default=1)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agentprovider",
            name="secret",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentsecret"
            ),
        ),
        migrations.CreateModel(
            name="AgentSendIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("client_key", models.UUIDField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source_message",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.message"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentSetupOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("profile_revision", models.PositiveIntegerField(default=1)),
                ("provider_config_version", models.PositiveIntegerField(null=True)),
                ("configuration_digest", models.CharField(default="", max_length=64)),
                ("descriptor_digest", models.CharField(default="", max_length=64)),
                ("descriptor", models.JSONField(default=dict)),
                ("phase", models.CharField(default="pending", max_length=30)),
                ("requirements", models.JSONField(default=list)),
                ("retry_key", models.UUIDField()),
                ("payload_digest", models.CharField(max_length=64)),
                ("claim_key", models.UUIDField(null=True)),
                ("lease_epoch", models.PositiveBigIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentprofile",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentprovider",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentProbeGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("profile_revision", models.PositiveIntegerField()),
                ("provider_config_version", models.PositiveIntegerField(null=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zerver.agentprovider",
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentrunner"
                    ),
                ),
                (
                    "setup_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentsetupoperation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_id", models.CharField(max_length=80)),
                ("command", models.JSONField()),
                ("cwd", models.CharField(max_length=512)),
                ("exit_code", models.IntegerField(null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("tree_hash", models.CharField(max_length=64)),
                ("timed_out", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentattempt"
                    ),
                ),
                (
                    "output_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="zerver.agentartifact"
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="agentartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__lte", 10485760)), name="agent_artifact_size_limit"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.UniqueConstraint(
                fields=("job", "client_key"), name="agent_input_client_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_message__isnull", False)),
                fields=("job", "source_message"),
                name="agent_input_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.UniqueConstraint(
                fields=("job", "sequence"), name="agent_input_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "delivery_state__in",
                        ("pending", "delivered", "applied", "delivery_uncertain", "cancelled"),
                    )
                ),
                name="agent_input_delivery_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_type__in", ["steering", "answer", "replan"])),
                name="agent_input_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinput",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="agent_input_sequence_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="agentauditevent",
            index=models.Index(fields=["job", "sequence"], name="zerver_agen_job_id_5a2405_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.UniqueConstraint(
                fields=("attempt", "event_id"), name="agent_event_attempt_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.UniqueConstraint(
                fields=("job", "event_id"), name="agent_event_job_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.UniqueConstraint(
                fields=("job", "sequence"), name="agent_event_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt_sequence__isnull", False)),
                fields=("attempt", "attempt_sequence"),
                name="agent_event_attempt_seq_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="agent_event_sequence_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("authority__in", ["server", "runner", "verifier", "publisher"])
                ),
                name="agent_event_authority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "proposed",
                            "authorized",
                            "started",
                            "succeeded",
                            "failed",
                            "outcome_unknown",
                            "cancelled",
                        ),
                    )
                ),
                name="agent_operation_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("consumed_at__isnull", False)),
                fields=("operation",),
                name="agent_approval_one_consumption",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "decision__in",
                        ("pending", "approved", "rejected", "expired", "cancelled", "consumed"),
                    )
                ),
                name="agent_approval_decision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("consumed_at__isnull", True),
                    models.Q(("approver__isnull", False), ("decision", "consumed")),
                    _connector="OR",
                ),
                name="agent_approval_consumption_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "consumed"), _negated=True),
                    ("consumed_at__isnull", False),
                    _connector="OR",
                ),
                name="agent_approval_consumed_time",
            ),
        ),
        migrations.AddIndex(
            model_name="agentoutbox",
            index=models.Index(
                fields=["realm", "status", "next_attempt_at"], name="zerver_agen_realm_i_0f72f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "processing", "delivered", "blocked"])
                ),
                name="agent_outbox_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentdispatchreceipt",
            constraint=models.UniqueConstraint(
                fields=("realm", "source_message", "profile", "trigger_kind"),
                name="agent_dispatch_trigger_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentdispatchreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "rejected"), ("job__isnull", True)),
                    models.Q(("decision__in", ["accepted", "needs_input"]), ("job__isnull", False)),
                    _connector="OR",
                ),
                name="agent_dispatch_job_decision",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrunner",
            index=models.Index(
                fields=["realm", "owner", "status"], name="zerver_agen_realm_i_a86125_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrunner",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("online", "offline", "unknown", "revoked"))),
                name="agent_runner_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrepository",
            constraint=models.UniqueConstraint(
                fields=("runner", "workspace_alias"), name="agent_repo_runner_alias_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("desired_state__in", ("draft", "enabled", "paused", "archived"))
                ),
                name="agent_profile_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "readiness_state__in",
                        ("unchecked", "checking", "ready", "needs_action", "error"),
                    )
                ),
                name="agent_profile_readiness_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_mode__in", ("answer", "code"))),
                name="agent_profile_job_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode", "acp"),
                    models.Q(("mode", "endpoint"), ("provider__isnull", False)),
                    _connector="OR",
                ),
                name="agent_profile_runtime_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_mode", "answer"),
                    ("default_repository__isnull", False),
                    _connector="OR",
                ),
                name="agent_profile_code_repo",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("desired_state", "enabled"), _negated=True),
                    ("enabled_revision__isnull", False),
                    _connector="OR",
                ),
                name="agent_profile_enable_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("enabled_revision__isnull", True),
                    ("enabled_revision__lte", models.F("revision")),
                    _connector="OR",
                ),
                name="agent_profile_enabled_not_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("readiness_revision__isnull", True),
                    ("readiness_revision__lte", models.F("revision")),
                    _connector="OR",
                ),
                name="agent_profile_ready_not_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version__gte", 1), ("revision__gte", 1)),
                name="agent_profile_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentpairing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["pending", "approved", "exchanged", "expired", "rejected"])
                ),
                name="agent_pairing_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentpairing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("owner__isnull", True),
                        ("realm__isnull", True),
                        ("runner__isnull", True),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("owner__isnull", False),
                        ("realm__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="agent_pairing_tenant_authority",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentpairing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["approved", "exchanged"]), _negated=True),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("owner__isnull", False),
                        ("realm__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="agent_pairing_approval_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentpairing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "exchanged"), _negated=True),
                    models.Q(("exchanged_at__isnull", False), ("runner__isnull", False)),
                    _connector="OR",
                ),
                name="agent_pairing_exchange_bound",
            ),
        ),
        migrations.AddIndex(
            model_name="agentjob",
            index=models.Index(
                fields=["realm", "status", "runner", "next_attempt_at"],
                name="zerver_agen_realm_i_2246dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentjob",
            index=models.Index(fields=["profile", "status"], name="zerver_agen_profile_dc1e76_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.UniqueConstraint(
                fields=("realm", "requester", "idempotency_key"),
                name="agent_job_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_message__isnull", False)),
                fields=("realm", "source_message", "profile", "trigger_kind"),
                name="agent_job_trigger_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "draft",
                            "queued",
                            "running",
                            "waiting_for_input",
                            "waiting_for_approval",
                            "blocked",
                            "verifying",
                            "cancel_requested",
                            "cancelled",
                            "interrupted",
                            "failed",
                            "completed",
                        ),
                    )
                ),
                name="agent_job_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phase__in", ("inspect", "plan", "edit", "verify", "review", "deliver"))
                ),
                name="agent_job_phase_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delivery_target", "answer"), ("job_kind", "answer")),
                    models.Q(("delivery_target__in", ["patch", "draft_pr"]), ("job_kind", "code")),
                    _connector="OR",
                ),
                name="agent_job_kind_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("admission_revision__gte", 1), ("version__gte", 1)),
                name="agent_job_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("profile__isnull", True),
                        ("provider__isnull", True),
                        ("repository__isnull", True),
                        ("runner__isnull", False),
                        ("target_kind", "runner"),
                    ),
                    models.Q(
                        ("profile__isnull", True),
                        ("provider__isnull", False),
                        ("repository__isnull", True),
                        ("runner__isnull", True),
                        ("target_kind", "provider"),
                    ),
                    models.Q(
                        ("profile__isnull", True),
                        ("provider__isnull", True),
                        ("repository__isnull", False),
                        ("runner__isnull", True),
                        ("target_kind", "repository"),
                    ),
                    models.Q(
                        ("profile__isnull", False),
                        ("provider__isnull", True),
                        ("runner__isnull", True),
                        ("target_kind", "profile"),
                    ),
                    _connector="OR",
                ),
                name="agent_grant_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("principal_group__isnull", True), ("principal_user__isnull", False)),
                    models.Q(("principal_group__isnull", False), ("principal_user__isnull", True)),
                    _connector="OR",
                ),
                name="agent_grant_one_principal",
            ),
        ),
        migrations.AddIndex(
            model_name="agentattempt",
            index=models.Index(
                fields=["runner", "active", "lease_expires_at"],
                name="zerver_agen_runner__a7a4c2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "number"), name="agent_attempt_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("job",),
                name="agent_attempt_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.UniqueConstraint(
                fields=("runner", "claim_key"), name="agent_attempt_claim_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "lease_epoch"), name="agent_attempt_epoch_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("process_state__in", ("starting", "active", "stopping", "stopped", "unknown"))
                ),
                name="agent_attempt_process_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_epoch__gte", 1), ("number__gte", 1)),
                name="agent_attempt_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), ("ended_at__isnull", True)),
                    models.Q(("active", False), ("ended_at__isnull", False)),
                    _connector="OR",
                ),
                name="agent_attempt_terminal_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprovider",
            constraint=models.CheckConstraint(
                condition=models.Q(("api_mode__in", ["chat_completions", "responses"])),
                name="agent_provider_api_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprovider",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("secret__isnull", True), ("local_credential_ref", ""), _connector="OR"
                ),
                name="agent_provider_one_secret",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentprovider",
            constraint=models.CheckConstraint(
                condition=models.Q(("config_version__gte", 1)),
                name="agent_provider_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsendintent",
            constraint=models.UniqueConstraint(
                fields=("realm", "sender", "client_key"), name="agent_send_sender_key_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsetupoperation",
            index=models.Index(
                fields=["realm", "runner", "phase"], name="zerver_agen_realm_i_45f891_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsetupoperation",
            constraint=models.UniqueConstraint(
                fields=("realm", "owner", "retry_key"), name="agent_setup_idempotency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsetupoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("claim_key__isnull", False)),
                fields=("runner", "claim_key"),
                name="agent_setup_claim_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsetupoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "phase__in",
                        [
                            "pending",
                            "claimed",
                            "probing",
                            "ready",
                            "needs_action",
                            "failed",
                            "stale",
                            "cancelled",
                        ],
                    )
                ),
                name="agent_setup_phase_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="agentverification",
            index=models.Index(
                fields=["attempt", "check_id", "tree_hash"], name="zerver_agen_attempt_3283f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentverification",
            constraint=models.CheckConstraint(
                condition=models.Q(("finished_at__gte", models.F("started_at"))),
                name="agent_verification_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("timed_out", False), models.Q(("exit_code", 0), _negated=True), _connector="OR"
                ),
                name="agent_verification_timeout_fail",
            ),
        ),
    ]
