# Generated by Django 5.2.14 on 2026-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0802_agent_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="logo_source",
            field=models.CharField(
                choices=[("D", "Default to Grow Team"), ("U", "Uploaded by administrator")],
                default="D",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="realm",
            name="night_logo_source",
            field=models.CharField(
                choices=[("D", "Default to Grow Team"), ("U", "Uploaded by administrator")],
                default="D",
                max_length=1,
            ),
        ),
    ]
