# Generated by Django 5.2.14 on 2026-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0804_agent_setup_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentartifact",
            name="audience_binding",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="audience_binding",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="stop_receipt",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentattempt",
            name="tool_rounds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentcheckpoint",
            name="audience_binding",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="audience_binding",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="audience_epoch",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="event_sequence",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="input_sequence",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="result_proposal",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="result_receipt",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="stop_target",
            field=models.CharField(default="cancelled", max_length=20),
        ),
        migrations.AddField(
            model_name="agentoperation",
            name="scope_binding",
            field=models.JSONField(default=dict),
        ),
    ]
