# Generated by Django 5.2.14 on 2026-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0805_agent_lifecycle_bindings"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinput",
            name="reconciliation_receipt",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="resume_checkpoint",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resume_jobs",
                to="zerver.agentcheckpoint",
            ),
        ),
    ]
