# Generated by Django 5.2.14 on 2026-09-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0806_agent_resume_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentverification",
            name="operation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="zerver.agentoperation"
            ),
        ),
    ]
