# Generated by Django 5.2.14 on 2026-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0807_agent_verification_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentoperation",
            name="local_receipt",
            field=models.JSONField(default=None, null=True),
        ),
    ]
