# Generated by Django 5.2.14 on 2026-09-21 20:19

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def backfill(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    intent = apps.get_model("zerver", "AgentSendIntent")
    intent.objects.filter(source_message__isnull=False).update(
        sent_message_id=models.F("source_message_id")
    )
    intent.objects.filter(source_message__isnull=True).update(identity_unavailable=True)


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0808_agent_local_reconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsendintent",
            name="identity_unavailable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agentsendintent",
            name="sent_message_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
