# Generated by Django 5.2.14 on 2026-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0809_agent_send_tombstone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agentprofile",
            name="agent_profile_code_repo",
        ),
        migrations.AddField(
            model_name="agentjob",
            name="draft_completion",
            field=models.JSONField(default=None, null=True),
        ),
    ]
