# Generated by Django 5.2.14 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zerver", "0810_agent_incomplete_code_profiles")]

    operations = [
        migrations.AddField(
            model_name="agentrunner",
            name="host_kind",
            field=models.CharField(
                choices=[("workstation", "workstation"), ("server", "server"), ("unknown", "unknown")],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agentrunner",
            name="metadata_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="default_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_for_realms",
                to="zerver.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="default_selected_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="default_selected_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agent_defaults_selected",
                to="zerver.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="default_selection_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="agentrunner",
            constraint=models.CheckConstraint(
                condition=models.Q(("host_kind__in", ["workstation", "server", "unknown"])),
                name="agent_runner_host_kind_valid",
            ),
        ),
    ]
