# Generated by Django 5.2.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zerver", "0811_agent_settings_defaults")]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="metadata_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentprovider",
            name="metadata_revision",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
