# Generated by Django 5.2.14 on 2026-09-22 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0812_agent_profile_provider_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "unique_together": {("realm", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaskBoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("order", models.PositiveIntegerField()),
                ("work_limit", models.PositiveIntegerField(default=None, null=True)),
                ("done_window_days", models.PositiveIntegerField(default=None, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="zerver.taskboard",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("board", "order")},
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("counter", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(default="", max_length=10000)),
                ("position", models.FloatField(default=0)),
                ("topic", models.TextField(default="")),
                ("labels", models.JSONField(default=list)),
                ("checklist", models.JSONField(default=list)),
                ("due_at", models.DateTimeField(default=None, null=True)),
                ("blocked", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(default=None, null=True)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agent_job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zerver.agentjob",
                    ),
                ),
                (
                    "agent_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zerver.agentprofile",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_cards",
                        to="zerver.message",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="zerver.stream"
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="zerver.taskboard",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="zerver.taskboardcolumn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("moved", "moved"),
                            ("edited", "edited"),
                            ("assigned", "assigned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("extra_data", models.JSONField(default=dict)),
                (
                    "acting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="zerver.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["board", "column", "position"], name="zerver_task_board_i_3e1de1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("realm", "counter"), name="task_counter_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["created", "moved", "edited", "assigned"])),
                name="task_history_kind_valid",
            ),
        ),
    ]
