# Generated by Django 5.2.14 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("zerver", "0818_agent_manage_mode")]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="instructions",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="team_instructions",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="agentrealmsettings",
            name="team_instructions_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentjob",
            name="follows_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zerver.agentjob",
            ),
        ),
    ]
